### ISSUE TITLE
mstrust() center could be list

### ISSUE THREAD

**Issue by dkaschek** [dkaschek/dMod#23]
It would be a nice feature to allow more than one center in mstrust(). It could be helpful to write additional as.parframe-methods for classes matrix, list and data.frame. Then center could be a parframe.

**Comment by wmader** [comment]
On 2016 M09 22, Thu 06:33:08 CEST dkaschek wrote:

> It would be a nice feature to allow more than one center in mstrust(). It
> could be helpful to write additional as.parframe-methods for classes
> matrix, list and data.frame. Then center could be a parframe.

Gute Idee. Mach ich nächste Woche.

Grüße,
Wolfgang
