### ISSUE TITLE
Symbolic sensitivities bug, if all states were fixed

### ISSUE THREAD

**Issue by marcusrosenblatt** [dkaschek/dMod#24]
prodSymb() produces error when dv = NULL. This in fact happens when user tries to a priori fix (argument fixed in odemodel) all states of a given model. Same is probably for the parameters.

Use an if statement and output warning!?

**Comment by dkaschek** [comment]
Thanks Marcus. The problem is within cOde. I fixed the function sensitivitiesSymb() in the cOde package and pushed it into the repo. I had it tested with a model where I fixed all states. Please pull and build cOde and try again. Let me know if it works for you.

**Comment by marcusrosenblatt** [comment]
Thank Daniel. Works fine for me now!
