### ISSUE TITLE
getParameters.combined

### ISSUE THREAD

**Issue by dlill** [dkaschek/dMod#26]
#There is a bug in getParameters(g*x)
library(dplyr) #for pipe
library(dMod)
## Model definition (text-based, scripting part)
f <- NULL %>%
  addReaction("A", "B", "k1*A", "translation") %>%
  addReaction("B",  "", "k2*B", "degradation") %>%
  as.eqnvec()

events <- eventlist(var = "A", time = 5, value = "A_add", method = "add")

x <- odemodel(f, events = events) %>% Xs

g <- Y(c(Bobs = "s1*B"), x, compile = T, modelname = "obsfn")

conditions <- c("a", "b")

# there is a bug in getParameters(g*x), it doesn't get the parameters from g
getParameters((g*x))
union(getParameters(g), getParameters(x))

**Comment by marcusrosenblatt** [comment]
Hi,

I get the same problem and identified the origin. When creating a composed object with "*" for example as g*x, the attribute "parameters" is always only handed over from the latter object (in our case x). Attributes are, however, used for output of getParameters(). I would fix that in *.fn but was not completely sure about possible consequences... I am checking this in now. Please undo it, if I am missing something!

Cheers,
Marcus

**Comment by marcusrosenblatt** [comment]
When creating a composed object with " * " for example as g * x, the attribute "parameters" is always only handed over from the latter object (in our case x).

**Comment by marcusrosenblatt** [comment]
Interestingly, g * p0 does not hand over parameters at all. Does this make sense!?

**Comment by dkaschek** [comment]
The return value of parameters(x) is determined in "\*.fn". Each section has a subsection "Generate mappings of ...". As Marcus said, the concatenated function always carries the parameters of the second function. That makes sense if the last function in a chain is the parameter transformation which, usually, has completely different parameters than the prd/obs functions.
I did not have a look yet at Marcus changes. But we need to decide combination for combination what the appropriate return value is, e.g. prd\*par differently from obs\*prd.

**Comment by dkaschek** [comment]
I had a quick look at Marcus changes. Generally using `union(pars1, pars2)` instead of `pars2` will cause problems. For example `getParameters(g*x*p)` should only return the parameters of `p`. Please correct.

**Comment by marcusrosenblatt** [comment]
I removed the changes except for the case obj*prd for which the issue occurred.

But why should getParameters(obj*prd*par) == getParameters(par)? Don't you need for example scalings in the observables here!?

**Comment by dkaschek** [comment]
There is a difference between `getParameters(g*x*p)` and `getParameters(g, x, p)`. For the first case, I am interested in the parameters that need to be specified for `p`, presuming that `p` will return all parameters necessary to feed into `x` and `g`. In general, the parameters of `p` (outerpars) can be completely different from the inner pars. It does not make sense to return innerpars instead of outerpars.
When I set up my parameter transformation, I usually use the command `innerpars <- getParameters(g, x, e)`.

**Comment by dlill** [comment]
I agree with Daniel and in the dMod.frame branch, I restored the original behaviour.

The only combination where it would make sense would be `(g*x)`, but I think it's easier to keep the convention that `getParameters(a*b*c*d*...*z)` always returns `getParameters(z).`

I suggest pointing this out in the documentation (will do it tomorrow myself), maybe even by an example and show the alternative to use `getParameters(g,x)` if one wants to get the inner parameters.
