### ISSUE TITLE
getParameters for classes eqn.list and eqn.vec

### ISSUE THREAD

**Issue by marcusrosenblatt** [dkaschek/dMod#27]
What about making function ```getParameters()``` applicable to classes eqn.list and/or eqn.vec?

**Comment by dkaschek** [comment]
The reason why this is not implemented is `forcings`. In the eqnlist or eqnvec you cannot distinguish between parameters and forcings. Only after registering forcings by the `forcings` argument in `odemodel()` the set of parameters if well defined.

**Comment by marcusrosenblatt** [comment]
I was not thinking about the ```eqn.list``` object that is handed over to ```odemodel()```. I meant the general class. You could than for example get all parameters of a certain entry in your ```trafo``` (would have been useful for my cluster stuff). But I see that it could lead to problems when the user applies it before ```odemodel()```.

Anyway in my case I can always use ```getSymbols()``` instead.
