### ISSUE TITLE
boolean argument for ```insert()``` and ```define()```

### ISSUE THREAD

**Issue by marcusrosenblatt** [dkaschek/dMod#28]
Hi folks ;-)

the argument ```conditionMatch``` for ```insert()``` and ```define()``` works pretty well in most cases. I wondered why we not (additionally) provide the possibility to specify a boolean argument that is based on the contents of ```covtable```!? The column names of ```covtable``` could be used as identifiers. 

I am thinking of something like
```trafo <- insert(trafo, "x~x_scale", conditionMatch=NULL, newArgument=(!is.na(siRNA) & 2ndStimulus > 10), x=c("scaleSTAT123"), scale = scale)```,

where ```siRNA``` and ```2ndStimulus``` are some of the column names in ```covtable```.

I am not yet sure about a clever implementation, since ```newArgument``` should probably be provided as a ```...``` argument.

For me something like this would be very helpful and more intuitive than ```conditionMatch```. But I also see advantages in ```conditionMatch```. It probably depends how you set up your model. So let me know what you think of this idea!?

Best,
Marcus

**Comment by dkaschek** [comment]
I use the `ifelse` function to accomplish something similar:
`trafo <- insert(trafo, "x~x_scale", x = "scaleSTAT123", scale = ifelse(!is.na(siRNA) & 2ndStimulus > 10, scale, "0"))`
In contrast to `if()` the `ifelse()` function takes a logical vector as input and returns a vector of the same length.

**Comment by marcusrosenblatt** [comment]
Ok, this looks reasonable. I can probably get into that... I will add one example line for that to the documentation!

**Comment by dlill** [comment]
I think it would still be nice to have the conditionConditions ( = newArgument ) option as it eases thinking when you can do one subset of conditions at a time and don't have to specify alternatives right away...
