### ISSUE TITLE
"intern" in compile

### ISSUE THREAD

**Issue by dlill** [dkaschek/dMod#30]
Wäre es mehrheitsfähig, in `compile()`, wo `system` aufgerufen wird, `intern = TRUE` zu setzen? Dann würde der ganze compiler-output nicht mehr gedruckt werden, wenn man es nicht will.

**Comment by marcusrosenblatt** [comment]
Das Problem ist bei mir noch nie aufgetreten, vermutlich da ich sowieso immer mit ```odemodel()``` compilieren lasse...
Insofern enthalte ich mich bei der Abstimmung ;-)

**Comment by dkaschek** [comment]
Mach es mit einem `verbose` Argument, das per default auf `FALSE` gesetzt ist.
