### ISSUE TITLE
IQRtools

### ISSUE THREAD

**Issue by dlill** [dkaschek/dMod#31]
Hi everyone, 

the newly introduced dependency IQRtools can be found here:

http://iqrtools.intiquan.com/

Best, Daniel

PS: Daniel, willst du mal Svenja adden? Dann kann sie auch die ganzen issues lesen. Ihr Name auf github ist svkemmer

**Comment by dkaschek** [comment]
Die Dependency dürfte es nicht mehr geben. Habe ich letztens abends noch rausgenommen. Mirjam hatte mich darauf aufmerksam gemacht.
