### ISSUE TITLE
conditional parameter value

### ISSUE THREAD

**Issue by paolacarrillob** [dkaschek/dMod#32]
Hi there, I am working on a simple piecewise ODE model. I would like to set a condition that a parameter a=0 if t<=t_on and a = value otherwise. I would also like to estimate t_on and a. Is there anyway I can define the ODE like that?
Thanks,

Paola

**Comment by dlill** [comment]
The best way to do this would be to define another state "a" which has derivative 0. Then, you can set the initial of "a" to zero and then replace this value via an event. 

You can also estimate the time and the value of the event:
myevent <- eventlist(var = "a", time = "t_on", value = "a_on" , method = "replace")
This event needs to be passed to odemodel()
mymodel <- odemodel(..., events = myevent)

**Comment by dlill** [comment]
and for the f-argument for odemodel you need to append 
f <- c(f_0, "a" = 0), where f_0 is your usual model

**Comment by paolacarrillob** [comment]
Thank you for the answer. One last question, in which version do I find the eventList class? My current version 0,4 doesn't have it

**Comment by dlill** [comment]
0.4.1 should have it. The current master branch at github has it. You can try
devtools::install_github("dkaschek/dMod")

**Comment by dlill** [comment]
you might also need to update cOde ( devtools::install_github("dkaschek/cOde") )

**Comment by paolacarrillob** [comment]
Thank you!
