### ISSUE TITLE
plotCombined(), plotData(), plotPrediction()

### ISSUE THREAD

**Issue by dkaschek** [dkaschek/dMod#35]
When conditions are numeric values or can interpreted as such, the plot functions do not work any more. The problem seems to have appeared with the introduction of dplyr in the plot functions.

**Comment by dlill** [comment]
Liegt wahrscheinlich an dieser Zeile in  _wide2long.list_:

  **numconditions <- suppressWarnings(as.numeric(conditions))**
  
  Was ist der Vorteil, wenn Conditions as.numeric gemacht werden?

**Comment by dkaschek** [comment]
Der ursprüngliche Grund, warum ich das mal eingefügt habe, hat sich glaube ich erübrigt. Bei meinen conditions ist es so, dass sie sich aus den Daten aus einer ID-Spalte ergeben und deshalb numerisch sind. Letzte Woche konnte ich damit noch ganz normal plotten. Heute nicht mehr.

**Comment by dlill** [comment]
Dann werde ich morgen versuchen, es in wide2long zu beheben. Meine Idee war, an die wide2long data.frames von data und prediction noch das condition.grid dranzuheften, damit man a) auch über kovariaten filtern kann und b) auch auf diese direkt zugreifen kann, indem man neue aesthetics definieren kann über aesthetics.

**Comment by dlill** [comment]
Habe jetzt wide2long geändert, jetzt geht das Plotten wieder. Falls du ein nichttriviales condition.grid hast, probier mal im plotCombined das Argument aesthetics = list(linetype = "covname") aus, oder für die Punkte covname == covvalue.

**Comment by dkaschek** [comment]
plotCombined() funktioniert immer noch nicht. Anscheinend wird `ymin = value - sigma` und `ymax = value + sigma` nicht korrekt nach unten weitergegeben. Jedenfalls beschwert sich `geom_errbar()`, dass er ymin und ymax nicht hat. 

Wenn ich die Zeile durch `geom_errbar(aes(ymin = value - sigma, ymax = value + sigma), data = data, width = 0)` ersetze, funktioniert es. So war es aber nicht gedacht, nehme ich an.

Ich habe keine Ahnung von rlang. Kannst du checken, woran das liegt?
