### ISSUE TITLE
data argument in normL2

### ISSUE THREAD

**Issue by marcusrosenblatt** [dkaschek/dMod#41]
Since the introduction of the possibility to specify lower limit of quantification (lloq), the data argument has to contain the column lloq. When it is of type `datalist`, everything works fine. However, to ensure backward compatibility, I would suggest to
1) Either automatically convert the data argument by `as.datalist()` within `normL2` or
2) output a warning when the argument is not of type `datalist` and no lloq column was provided

Took me a while to figure this out, so could be in favor for others ;-)

**Comment by dkaschek** [comment]
The idea was that datalist() and as.datalist() ensure the backward compatibility. Indeed, when `mydata` is a data frame without lloq information, `as.datalist(mydata)` will generate the lloq column and will impute it with `-Inf`.

The documentation of `normL2(data, )` says that `data` is expected to be an object of class `datalist` ;-)

**Comment by marcusrosenblatt** [comment]
Well yes. I know ;-) But not all "old" code was written like this. The point is that the error message one obtains, if `data` is no `datalist` is just not very meaningful and this I would like to change... If you agree ;-)

**Comment by dlill** [comment]
I suggest moving all consistency checks to dMod.frame
;-)

**Comment by marcusrosenblatt** [comment]
In the meantime I agree on this. ;-)
