### ISSUE TITLE
Feature request: Include ordering column in as.parframe

### ISSUE THREAD

**Issue by burgerga** [dkaschek/dMod#44]
Currently I'm using mstrust with 2000 fits and when I get the results back I have no clue what the range of values is I'm getting.  So sometimes when I do 

```
plotValues(myframe, tol = 0.01, value < 100)
# or
plotPars(myframe, tol = 0.01, value < 100)
```
I get nothing, and sometimes I get an error because I get everything :P

Often I just want to have a look at the best 10 or 50, so what I'm doing now is

```
plotValues(myframe %>% rowid_to_column("rank"), tol = 0.01, rank <= 20)
```

Maybe it is useful to include this column already in `as.parframe`?

**Comment by burgerga** [comment]
```
plotValues(myframe %>% head(20), tol = 0.01)
```
also works of course, maybe I was overthinking it 😬

**Comment by dkaschek** [comment]
I was just about to comment that it was sufficient to use
```
plotValues(myframe[1:20, ])
```

Using `head()` is equivalent. Keep in mind that `parframe`s are data frames with additional attributes to keep track of the variables and meta information. Operations with `[i, j]` are implemented in dMod, dplyr verbs are (currently) not.
