### ISSUE TITLE
Options for constraintExp()

### ISSUE THREAD

**Issue by dkaschek** [dkaschek/dMod#5]
Instead of "sigma" and "k" let the user define "limit" and "borderwidth" where
"limit" is defined by the parameter distance where the prior exceeds qchisq(p = 0.95, df = 1)
"borderwidth" is the distance from limit to the parameter where the prior is below a threshold, e.g. 0.1

**Comment by marcusrosenblatt** [comment]
Since introduction of boundary specification for trust, constraintExp() is unnecessary.
