### ISSUE TITLE
Question on forcing  a parameter relationship for trust fitting

### ISSUE THREAD

**Issue by paulrbuckley** [dkaschek/dMod#59]
Hi,

Say I have two parameters, where the value of one depends on the value of another e.g;

a = 0.1
b = (a* 5)

What is the best way to inform trust() to adhere to this relationship? I've tried setting this in a parameter transformation,, where the objective function is created by (predictionFunction * parameterTransformation). The parameter transformation captures the relationship required but the argument vector returned from trust has not preserved this relationship? Example code is given as below;

```
p.transform = eqnvec() %>% 
  define("x~x", x= c(names(parameters))) %>%
  insert("x~5*a", x="b") %>%
   P(condition="fitting")

obj=normL2(fittingData.for.dMod,predictionFunction*p.transform)
# # 
# # 
# # 
 mu=mu %>% as.parvec()
 
myfit = lapply(1, function(i) {
  trust(obj + constr, mu, rinit = 1, rmax = 10000,fixed=fixed,parlower = lowerPars,parupper = parUpper,iterlim = 300)
})

```
where constr, lowerPars and parUpper are defined previously.. 

any help would be appreciated

cheers, P

**Comment by paulrbuckley** [comment]
also, names(parameters) defines the 'a' parameter

**Comment by marcusrosenblatt** [comment]
Hi Paul,

as far as I can see, you are doing it right.
E.g. define the transformation like:
```
p.transform = eqnvec() %>% 
     define("x~x", x= c("a", "b")) %>%
     insert("x~5*a", x="b")%>%
     P(condition="fitting")
```
Then
```
attr(p.transform, "parameters")
```
gives you back only parameter a.
So you can define a vector `mypars <- c(a=2)` and calculate `p.transform(mypars)`

Similarly trust will take over this information from the `obj `argument.


By the way: We always recommend to define parameters on the log-scale, e.g. via:
```
p.transform = eqnvec() %>% 
     define("x~x", x= c("a", "b")) %>%
     insert("x~5*a", x="b")%>%
     insert("x~10**(x)", x = .currentSymbols)
``

**Comment by marcusrosenblatt** [comment]
By the way: We always recommend to define parameters on the log-scale, e.g. via:
<- insert(trafoL, "x~exp(x)", x = .currentSymbols)

**Comment by paulrbuckley** [comment]
thanks Marcus. I've just had a fiddle and what you sent works for me, whereas in my real scenario, it doesnt work. I think this is due to the order of the parameters, as alphabetically, the parameter which requires the transformation is ordered before the latter one. 

Any chance it could be related to the order? With my data, if i try to reproduce your code, I receive the same error that occurs if we swap a and b as you have described above e.g:

```
 p.transform = eqnvec() %>% 
     define("x~x", x= c("a", "b")) %>%
     insert("x~5*b", x="a")%>%
     P(condition="fitting")
 
 mypars <- c(a=2)
 
 p.transform(mypars)
```

**Comment by marcusrosenblatt** [comment]
Well, in your last example you need to define parameter b instead of a in mypars:

```
p.transform = eqnvec() %>% 
     define("x~x", x= c("a", "b")) %>%
     insert("x~5*b", x="a")%>%
     P(condition="fitting")
 
 mypars <- c(b=2)
 
 p.transform(mypars)
```

To see what is going on, you may look at the parameter transformation itself:
```
p.transform = eqnvec() %>% 
     define("x~x", x= c("a", "b")) %>%
     insert("x~5*b", x="a")
p.transform
```

Everything on the right side (Outer) needs to be given in the parameter vector. In other words, it is seen by the optimizer.

**Comment by paulrbuckley** [comment]
Hi, yes sorry that's me being dim.. that now works for p.transform() using the parameter vector. I hadn't passed the initial conditions.

I'm still confused, as the parameter vector given, which now appropriately calculates the parameter in p.transform() as above, when passed to obj, the parameter relationship isnt preserved i.e;

```
constr <- constraintL2(mu = mu, sigma = 1)

 obj=normL2(fittingData.for.dMod,(predictionFunction*p.transform)) 
 
myfit = lapply(1, function(i) {
  trust(obj+constr, mu, rinit = 1, rmax = 10000,fixed=fixed,parlower = lowerPars,parupper = parUpper,iterlim = 300)
})

```

strangely everything runs fine, and the fit converges but the resulting myfit[[1]]$argument does not have parameters where the relationship is preserved. The transformation is appropriately defined and passed to normL2, but strangely doesn't work in trust().. From the a,b example, how would you then pass it to trust(), just to confirm i've not missed something..

**Comment by paulrbuckley** [comment]
the parameters of interest are contained in vectors 'mu', 'lowerPars' and 'parUpper'..

**Comment by marcusrosenblatt** [comment]
I think you are mixing up the parameters of the optimization with the parameters of the model. Let us take the last example, where we replaced a=5*b. After you have done your this transformation, for the optimizer there is no parameter "a" anymore. Probably you get some value in myfit[[1]]$argument because it is in your constraintL2 norm. Make sure that your fixed, lowerPars and parUpper arguments as well as mu only have a parameter "b" but no "a" anymore.

Still if you take your result and calculate p.transform(myft[[1]]$argument) you should definitely have parameters with the desired property.

**Comment by paulrbuckley** [comment]
Aaaaaaaah you're right, amazing thank you so much, all working now! I still had the parameter in the mu, lowerPars and parUpper. I hadn't understood the nature of the transformation in that manner.

Thanks again!

Paul
