### ISSUE TITLE
Save all results of msnarrow in one fitlist.

### ISSUE THREAD

**Issue by ReedWood** [dkaschek/dMod#6]
Right now, the fitlist returned from msnarrow only holds the results of the its last call to mstrust. It might be a good idea to return a fitlist which holds the results of all fits.

**Comment by dkaschek** [comment]
Ja, gute Idee. Ich würde eine Spalte "narrow" vorne mit dran machen mit Werten 0, 1, 2, etc. für den narrow-Schritt.

**Comment by ReedWood** [comment]
OK, dann machen wir das so.
