### ISSUE TITLE
more then one forcing implementation

### ISSUE THREAD

**Issue by motyocska** [dkaschek/dMod#66]
Dear Daniel,

wanted to ask a quick question about how forcings are to be set up when more then one forcings name exists? here is a modified example from package examples (see "G" for forc2 instead of "F" for package example):

f <- addReaction(NULL, from = "", to = "A", rate = "switch*F*G", description = "production")
f <- addReaction(f   , from = "A", to = "", rate = "k*A", description = "degradation")
print(f)
model <- odemodel(f, forcings = c("F","G"), fixed = "switch")
print(model)
# create forcings
forc1 <- data.frame(name = "F", time = seq(0,5, 0.1), value = sin(seq(0,5,0.1)))
forc2 <- data.frame(name = "G", time = seq(0,5, 0.1), value = exp(-seq(0,5,0.1)))
forc3 <- data.frame(name = "F", time= 0,              value = 0.1)
x <- Xs(model, forc1, condition = "forc1") + 
  Xs(model, forc2, condition = "forc2") + 
  Xs(model, forc3, condition = "forc3")
g <- Y(c(out1 = "F * A", out2 = "F", out3 = "G"), x)
times <-  seq(0,5, 0.001)
pars <- setNames(runif(length(getParameters(x))), getParameters(x))
pred <- (g*x)(times, pars) 

which yields error message:
Error in forcings[[i]][1, 2] : subscript out of bounds

could you please help identify what I may be doing wrong when trying to assign more then one forcings?

thank you,

Andras

**Comment by dlill** [comment]
A forcing sets the variable x to a specific value at a given time. So what you are doing here is saying that "F" should be both value 0 and 0.1 at time = 0, i.e. forc1 and forc3 contradict each other. For each variable, you can have only one forcing at the same time. So, what you can do is rename the variable "F" from forc3 to "F2" to resolve this contradiction.

Furthermore, the use of forcings is discouraged since they don't force that the integrator evaluates switching values at the exact switch times. It's usually better to go with events, which are more numerically accurate.

**Comment by motyocska** [comment]
Hi Daniel Lill,

the issue will continue to exists when I change F to F2 in forc3, see code below. The example I provided above is the one that is included in the odemodel function help page as part of the package except to change forc2 to "G" as in my own problem example there are always >2 forcings specified . When I reviewed the example in the odemodel help page I did have similar concern re "contradiction" forc1-forc2-forc3 (they are all forcings "F" there....) but if you are to run the example then you will get predictions for each condition,  even though it "appears contradictory", although I feel I may be missing something there, too.... Thanks for the pointer re forcings, had my share of trouble re intended time of forcing vs integrator switching.... To me the issue appears to be that forcing "G" is not recognized by the system for some reason as the error message appears after adding a second forcing with a different name to the system? Thanks, Andras

f <- addReaction(NULL, from = "", to = "A", rate = "switch*F*F2", description = "production")
f <- addReaction(f   , from = "A", to = "", rate = "k*A*G", description = "degradation")
print(f)

model <- odemodel(f, forcings = c("F","G","F2"), fixed = "switch")
print(model)


forc1 <- data.frame(name = "F", time = seq(0,5, 0.1), value = sin(seq(0,5,0.1)))
forc2 <- data.frame(name = "G", time = seq(0,5, 0.1), value = exp(-seq(0,5,0.1)))
forc3 <- data.frame(name = "F2", time= 0,              value = 0.1)


x <- Xs(model, forc1, condition = "forc1") + 
  Xs(model, forc2, condition = "forc2") + 
  Xs(model, forc3, condition = "forc3")

g <- Y(c(out1 = "F * A", out2 = "F", out3 = "G", out4 = "F2"), x)

times <-  seq(0,5, 0.001)
pars <- setNames(runif(length(getParameters(x))), getParameters(x))

pred <- (g*x)(times, pars)

**Comment by dlill** [comment]
Hey, yeah, sorry my answer was only partially correct. It's totally possible to have different forcings per condition, but you must take care to make each variable available to each condition. For example, variable "G" wasn't defined in condition "forc1". Maybe the following code clarifies that a bit for you?

```
library(dMod)
td <- tempdir()
setwd(td)

f <- addReaction(NULL, from = "", to = "A", rate = "switch*F*F2", description = "production")
f <- addReaction(f , from = "A", to = "", rate = "k*G", description = "degradation")
print(f)

model <- odemodel(f, forcings = c("F","G","F2"), fixed = "switch")
print(model)

# All forcings in same experimental condition
forc1 <- data.frame(name = "F", time = seq(0,5, 0.5), value = sin(seq(0,5,0.5)))
forc2 <- data.frame(name = "G", time = seq(0,5, 0.5), value = exp(-seq(0,5,0.5)))
forc3 <- data.frame(name = "F2", time= 0, value = 0.1)
x <- Xs(model, forcings = rbind(forc1,forc2,forc3)) 
g <- Y(c(out1 = "F * A", out2 = "F", out3 = "G", out4 = "F2"), x)
times <- seq(0,5, 0.001)
pars <- setNames(runif(length(getParameters(x))), getParameters(x))
pred <- (g*x)(times, pars)
plot(pred)

# Different forcings in different experimental condition
forc1_C2 <- data.frame(name = "F", time = seq(0,5, 0.5), value = sin(-seq(0,0.2,0.5)))
forc2_C2 <- data.frame(name = "G", time = seq(0,5, 0.5), value = sin(-seq(0,5  ,0.5)))
forc3_C2 <- data.frame(name = "F2", time= 0, value = 100)
x <-     Xs(model, forcings = rbind(forc1,forc2,forc3)         , condition = "C1") # Old forcings 
x <- x + Xs(model, forcings = rbind(forc1_C2,forc2_C2,forc3_C2), condition = "C2") # New forcings Condition 2
g <- Y(c(out1 = "F * A", out2 = "F", out3 = "G", out4 = "F2"), x)
times <- seq(0,5, 0.001)
pars <- setNames(runif(length(getParameters(x))), getParameters(x))
pred <- (g*x)(times, pars)
plot(pred)

```

**Comment by motyocska** [comment]
yes that is it! thanks for the help!

**Comment by motyocska** [comment]
closing...
